[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
web3_todo_app = "9VELjY4xnvMWThciCAuMDZNiDYSCd3341BD7PmU1UxwC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vscode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
